/**
 * Il catalogo inglese del modulo ACCESSO (/benvenuto e login).
 *
 * Nato dallo spacchettamento di en.ts (passo C, ARCHITETTURA.md, 23
 * agosto 2026). Chiave = frase italiana esatta nel codice; le regole di
 * traduzione sono nel commento di en.ts. Una voce per riga, sempre
 * "chiave": "valore", — verify-i18n legge questo formato.
 */
export const ACCESSO: Record<string, string> = {
  "Feedback": "Feedback",
  "Inizia": "Start",
  "Dove vuoi tenere\nil tuo diario?": "Where do you want\nto keep your diary?",
  "Puoi cambiare idea dopo. Quello che hai scritto viene con te.": "You can change your mind later. What you have written comes with you.",
  "Gratis, per sempre": "Free, forever",
  "Le tue giornate restano qui. Nessun account, nessun server, nessuno che possa leggerle. Nemmeno io.": "Your days stay here. No account, no server, nobody who can read them. Not even me.",
  "Scrivi la giornata, quando vuoi": "Write your day, whenever you want",
  "Obiettivi, peso, sonno, umore": "Goals, weight, sleep, mood",
  "Mese e Memo": "Month and Memo",
  "Backup su file, quando vuoi tu": "Backup to a file, whenever you want",
  "Niente racconto a voce": "No voice journaling",
  "Niente titoli, sintesi e recap AI": "No AI titles, summaries or recaps",
  "Un dispositivo solo": "One device only",
  "preparo...": "getting ready...",
  "inizia gratis": "start free",
  "Nella versione gratis scrivi a mano: niente racconto a voce e niente AI.": "In the free version you write by hand: no voice journaling and no AI.",
  "Non chiedermelo piu": "Do not ask me again",
  "Va bene. Quando vorrai passare a premium, potrai farlo dalle Impostazioni.": "All right. Whenever you want to go premium, you can do it from Settings.",
  "Nel cloud, con l'AI": "In the cloud, with AI",
  "Il diario ti segue ovunque. Racconti a voce e ci pensa lui a scriverlo, riassumerlo e ricordartelo.": "Your diary follows you everywhere. You talk, it writes it down, sums it up and remembers it for you.",
  "Tutto quello della versione gratis": "Everything in the free version",
  "Racconti a voce, si trascrive da solo": "Speak, and it transcribes itself",
  "Titolo, sintesi e macro-aree della giornata": "Title, summary and areas of the day",
  "Recap mensili, semestrali, annuali": "Monthly, half-yearly and yearly recaps",
  "Mac, iPhone, iPad sempre allineati": "Mac, iPhone and iPad always in sync",
  "primo mese incluso": "first month included",
  "Nella versione gratis nessun dato lascia il dispositivo: non c'e un server a cui mandarli.": "In the free version no data leaves the device: there is no server to send it to.",
  "Nella versione premium le tue giornate vengono salvate cifrate e il testo passa dai modelli AI per essere riassunto. Puoi cancellare tutto in qualsiasi momento.": "In the premium version your days are stored encrypted and the text goes through AI models to be summarised. You can delete everything at any time.",
  "Il codice": "The code",
  "Sei cifre inviate a": "Six digits sent to",
  "Controllo...": "Checking...",
  "Entra": "Enter",
  "Non arriva? Guarda nello spam, oppure": "Not arriving? Check your spam, or",
  "invio...": "sending...",
  "chiedine un altro": "ask for another one",
  "Cambia email": "Change email",
  "Bentornato": "Welcome back",
  "Inserisci l'email che hai usato l'ultima volta: ti mando un codice.": "Enter the email you used last time: I will send you a code.",
  "tu@dominio.com": "you@domain.com",
  "Sto inviando...": "Sending...",
  "Mandami il codice": "Send me the code",
  "Il codice vale un'ora.": "The code is valid for one hour.",
  "Non mostrare piu questo messaggio": "Do not show this message again",
  // La proposta Face ID dopo il codice a sei cifre (1 settembre 2026).
  "Vuoi usare Face ID?": "Want to use Face ID?",
  "Il diario si apre col tuo volto, senza codice. Puoi cambiare idea quando vuoi dalle Impostazioni.":
    "Your diary opens with your face, no code needed. You can change your mind anytime from Settings.",
  "Non te lo chiederemo piu": "We will not ask you again",
  "Se vuoi attivare Face ID, basta farlo dalle Impostazioni.":
    "If you want Face ID, you can turn it on from Settings.",
  "Attiva Face ID": "Turn on Face ID",
  "Non ora": "Not now",
  "Capito": "Got it",
  "Attivalo ora": "Turn it on now",
  "Un attimo...": "One moment...",
  // --- la cassaforte: le parole e il dispositivo nuovo (R8) ---
  "Il tuo codice di recupero": "Your recovery code",
  "Otto parole. Sono la chiave del tuo diario.": "Eight words. They are the key to your diary.",
  "Da adesso ogni giornata viene chiusa a chiave sul telefono prima di partire: sul server arriva un blocco illeggibile, e nessuno, nemmeno chi ha fatto questa app, puo aprirlo.":
    "From now on every day is locked on your phone before it leaves: the server receives an unreadable block, and nobody, not even the person who made this app, can open it.",
  "Se perdi queste parole e perdi tutti i tuoi dispositivi, il diario non lo recupera nessuno. Neanche noi.":
    "If you lose these words and you lose all your devices, nobody can recover the diary. Not even us.",
  "Fai uno screenshot adesso": "Take a screenshot now",
  "o copiale: tienile in un posto che apri solo tu.": "or copy them: keep them somewhere only you can open.",
  "Copia le parole": "Copy the words",
  "Copiate": "Copied",
  "Le ho salvate": "I have saved them",
  "Ho capito, continua": "Got it, continue",
  "Il tuo diario e chiuso a chiave": "Your diary is locked",
  "Ci sono {n} giornate, dal {dal}. Questo dispositivo non ha la chiave.": "There are {n} days, since {dal}. This device does not have the key.",
  "Questo dispositivo non ha la chiave del tuo diario.": "This device does not have the key to your diary.",
  "Scrivi le otto parole del codice di recupero, nell'ordine. Le hai ricevute quando hai creato l'account.":
    "Type the eight words of your recovery code, in order. You received them when you created the account.",
  "albero finestra dodici ...": "albero finestra dodici ... (the words are Italian)",
  "Le maiuscole e gli accenti non contano. Puoi incollarle tutte insieme.": "Capitals and accents do not matter. You can paste them all at once.",
  "La parola numero {n} non esiste nell'elenco. Controlla: \"{parola}\".": "Word number {n} is not in the list. Check: \"{parola}\".",
  "Servono {n} parole: ne hai scritte {q}.": "{n} words are needed: you typed {q}.",
  "Le parole esistono tutte, ma non nell'ordine giusto o non tutte di questo diario. Ricontrolla l'ordine.":
    "All the words exist, but not in the right order or not all from this diary. Check the order again.",
  "Queste parole sono di un altro diario: non aprono questo.": "These words belong to another diary: they do not open this one.",
  "Apri il diario": "Open the diary",
  "Apro...": "Opening...",
  "Non ho il codice": "I do not have the code",
  "Senza il codice, questo dispositivo non puo aprire il diario.": "Without the code, this device cannot open the diary.",
  "Non esiste un \"ho dimenticato la password\": la chiave non ce l'abbiamo, e per questo il diario e tuo e basta.":
    "There is no \"I forgot my password\": we do not have the key, and that is why the diary is yours and nobody else's.",
  "Le strade che restano:": "The ways that remain:",
  "Un iPhone, iPad o Mac con lo stesso Apple ID che ha gia aperto il diario: la chiave arriva da sola col portachiavi di iCloud, e da li puoi rivedere le parole in Impostazioni > Cassaforte.":
    "An iPhone, iPad or Mac with the same Apple ID that has already opened the diary: the key arrives by itself through iCloud Keychain, and from there you can see the words again in Settings > Vault.",
  "Un file di backup salvato in passato: si importa e si legge da qui.": "A backup file saved in the past: import it and read it from here.",
  "Ricominciare da zero, con un diario nuovo e un codice nuovo.": "Start over, with a new diary and a new code.",
  "Le {n} giornate chiuse restano sul server, illeggibili, finche non le cancelli tu.": "The {n} locked days stay on the server, unreadable, until you delete them.",
  "Ricomincia da zero": "Start over",
  "Sicuro? Le {n} giornate chiuse non si potranno piu leggere, da nessun dispositivo.": "Sure? The {n} locked days will no longer be readable, from any device.",
  "Sicuro? Il diario riparte vuoto, con un codice nuovo.": "Sure? The diary starts again empty, with a new code.",
  "Si, ricomincia da zero": "Yes, start over",
  "Un diario nuovo. Otto parole nuove.": "A new diary. Eight new words.",
  "Le tue giornate, anche altrove.": "Your days, elsewhere too.",
  "Metti una email: le giornate salgono chiuse a chiave ogni notte e le ritrovi su iPad e sul computer. Ti mando un codice di sei cifre. Mai una password.": "Add an email: your days go up locked every night and you find them on iPad and on the computer. I will send you a six-digit code. Never a password.",
  "Le giornate che hai gia scritto qui restano, e salgono al primo accesso.": "The days you already wrote here stay, and go up at first sign-in.",
};
