/**
 * Il catalogo inglese del modulo IMPOSTAZIONI (pannelli, tema, dati, consumi AI).
 *
 * Nato dallo spacchettamento di en.ts (passo C, ARCHITETTURA.md, 23
 * agosto 2026). Chiave = frase italiana esatta nel codice; le regole di
 * traduzione sono nel commento di en.ts. Una voce per riga, sempre
 * "chiave": "valore", — verify-i18n legge questo formato.
 */
export const IMPOSTAZIONI: Record<string, string> = {
  "Premium fino al {data}": "Premium until {data}",
  "Le giornate che hai gia scritto qui salgono nel cloud al primo accesso.": "The days you already wrote here move to the cloud on your first sign-in.",
  "Gestisci abbonamento": "Manage subscription",
  "Apple": "via Apple",
  "Chiedo ad Apple...": "Asking Apple...",
  "Premium ripristinato.": "Premium restored.",
  "Niente da ripristinare.": "Nothing to restore.",
  "{n} giorni gratis": "{n} days free",
  "poi": "then",
  "Si attiva dall'app per iPhone": "Activated from the iPhone app",
  "Pacchetto": "Build",
  "aggiungi": "add",
  "togli": "remove",
  "Non hai mai fatto un backup": "You have never made a backup",
  "Non fai un backup da {n} giorni": "You have not made a backup in {n} days",
  "Le tue {n} giornate esistono solo su questo dispositivo. Se si rompe o lo formatti, non c'e nessuna copia da nessuna parte: non esiste un server dove cercarle. Esporta il file e mettilo dove tieni le cose che non vuoi perdere.": "Your {n} days exist only on this device. If it breaks or you wipe it, there is no copy anywhere: there is no server to look on. Export the file and put it where you keep the things you do not want to lose.",
  "Errore nella rimozione": "Removal error",
  "Tracker neutri, niente voti: rispondono a “oggi l'ho fatto?” e basta. Compaiono nella giornata come caselle da accendere.": "Neutral trackers, no grades: they answer “did I do it today?” and nothing else. They show up in your day as boxes to tick.",
  "Attivi . salvo...": "Active . saving...",
  "Attivi": "Active",
  "Nessun obiettivo": "No goals",
  "Aggiungine uno qui sotto: comparira subito nella giornata.": "Add one below: it will show up in your day right away.",
  "Aggiungi un obiettivo...": "Add a goal...",
  "Nuovo obiettivo": "New goal",
  "Il tema cambia solo come si vede l'app. Le tue giornate non le tocca nessuno.": "The theme only changes how the app looks. Nobody touches your days.",
  "la telefonata rimandata": "the phone call put off",
  "Trentadue minuti, e una frase alla fine.": "Thirty-two minutes, and one sentence at the end.",
  "attivo": "active",
  "Ogni tema esiste in chiaro e in scuro, e passa un controllo automatico sul contrasto: un tema che rende il testo illeggibile non diventa selezionabile.": "Every theme exists in light and dark, and passes an automatic contrast check: a theme that makes text unreadable never becomes selectable.",
  "Chiaro": "Light",
  "Scuro": "Dark",
  "Sistema": "System",
  "Ch": "Li",
  "Sc": "Da",
  "Sist": "Sys",
  "Nessuna riga del tuo diario e mai uscita da questo dispositivo.": "Not one line of your diary has ever left this device.",
  "Le tue giornate vivono sul tuo account e ti seguono su ogni dispositivo.": "Your days live on your account and follow you on every device.",
  "Dove stanno": "Where they are",
  "Non c'e un account, non c'e un server, non c'e niente da chiedere di cancellare. L'app non fa nemmeno una richiesta di rete.": "There is no account, no server, nothing to ask anyone to delete. The app does not even make one network request.",
  "Se il dispositivo si rompe": "If the device breaks",
  "Il diario e finito. Non esiste una copia da nessuna parte: l'unica rete di salvataggio e il backup che esporti tu.": "The diary is gone. There is no copy anywhere: the only safety net is the backup you export yourself.",
  "Cosa esce da qui": "What leaves this device",
  "Niente": "Nothing",
  "Voce, riassunti e recap sono spenti in questa modalita proprio perche girerebbero su un server.": "Voice, summaries and recaps are off in this mode precisely because they would run on a server.",
  "Sul tuo account, nel cloud": "On your account, in the cloud",
  "Ti seguono su ogni dispositivo dove fai l'accesso. Il backup qui sopra resta una copia in piu, tua.": "They follow you on every device you sign in on. The backup above stays an extra copy, yours.",
  "Quello che chiedi tu": "What you ask for",
  "Registrazione, riassunto e recap passano da un server per essere elaborati. Il resto no.": "Recording, summary and recaps go through a server to be processed. Nothing else does.",
  "Come il dispositivo": "Same as the device",
  "Ora sarebbe {lingua}.": "Right now that would be {lingua}.",
  "Cambia solo le parole dell'app. Quello che hai scritto tu resta come l'hai scritto.": "It only changes the app's words. What you wrote stays exactly as you wrote it.",
  "Lingua": "Language",
  "Torna a Impostazioni": "Back to Settings",
  "Backup esportato: {n} {giornate}. Mettilo dove tieni le cose che non vuoi perdere.": "Backup exported: {n} {giornate}. Put it where you keep the things you do not want to lose.",
  "Export non riuscito.": "Export failed.",
  "Import non riuscito.": "Import failed.",
  "Fatto. Questo dispositivo non contiene piu nessuna giornata.": "Done. This device no longer holds a single day.",
  "Cancellazione non riuscita.": "Deletion failed.",
  "Ospite": "Guest",
  "Questo dispositivo": "This device",
  "Come funziona e come si vede il tuo diario.": "How your diary works and how it looks.",
  "Apri Recap": "Open Recap",
  "Le tue giornate, raccontate.": "Your days, told.",
  "Mensili, semestrali, annuali. Una prosa narrativa che rilegge i tuoi mesi senza giudizio.": "Monthly, half-yearly, yearly. Narrative prose that reads your months back to you without judgement.",
  "Nessun recap generato ancora": "No recap generated yet",
  "Il diario": "The diary",
  "Le caselle che accendi ogni giorno.": "The boxes you tick every day.",
  "attivi": "active",
  "Lingua e aspetto": "Language and look",
  "Al primo avvio segue la lingua del dispositivo.": "On first launch it follows the device language.",
  "automatica": "automatic",
  "Tema": "Theme",
  "{n} temi inclusi, tutti in chiaro e in scuro.": "{n} themes included, all in light and dark.",
  "Chiaro o scuro": "Light or dark",
  "Vale per qualsiasi tema. Con Sistema segue il dispositivo.": "Applies to any theme. With System it follows the device.",
  "I tuoi dati": "Your data",
  "Esporta un backup": "Export a backup",
  "Un solo file con tutto: giornate, obiettivi, metriche, Memo.": "One file with everything: days, goals, metrics, Memo.",
  "esporto...": "exporting...",
  "Importa un backup": "Import a backup",
  "Aggiunge le giornate che mancano. Quelle che hai gia non le tocca.": "It adds the days you are missing. It never touches the ones you already have.",
  "importo...": "importing...",
  "Dove sono le mie giornate": "Where my days are",
  "Cosa esce da questo dispositivo, e cosa no.": "What leaves this device, and what does not.",
  "Account": "Account",
  "Dove": "Where",
  "Email": "Email",
  "Ospite (cloud)": "Guest (cloud)",
  "Piano": "Plan",
  "Gratis": "Free",
  "Versione": "Version",
  "Esci dall'account": "Log out",
  "esco...": "logging out...",
  "Esco...": "Logging out...",
  "Zona pericolosa": "Danger zone",
  "Cancella tutte le giornate": "Delete all days",
  "Sicuro? Le elimina da questo dispositivo. Non si torna indietro.": "Sure? This deletes them from this device. There is no way back.",
  "Da questo dispositivo. Non si torna indietro.": "From this device. There is no way back.",
  "cancello...": "deleting...",
  "si, cancella": "yes, delete",
  "Passa a Premium": "Go Premium",
  "Dimensione del testo": "Text size",
  "Ingrandisce tutta l'app, non solo le scritte.": "Makes the whole app bigger, not just the words.",
  "Ingrandisce tutta l'app: scritte, tasti e spazi insieme. Cosi niente si accavalla.": "Makes the whole app bigger: words, buttons and spacing together. That way nothing overlaps.",
  "Anteprima": "Preview",
  "Torna alla misura normale": "Back to the normal size",
  "Quota inclusa nell'abbonamento": "Quota included in your subscription",
  "{n} token usati questo mese. La quota si azzera il primo del mese.": "{n} tokens used this month. The quota resets on the first of the month.",
  "Moduli": "Modules",
  "Sezioni in piu: palestra, cibo, sonno.": "Extra sections: gym, food, sleep.",
  "nessuno": "none",
  "Presto": "Coming soon",
  "presto": "soon",
  "Sezioni in piu, accese solo se le vuoi. Quella che accendi per ultima prende il quarto posto nella barra in basso; sul computer ci sono tutte nella colonna di sinistra.": "Extra sections, on only if you want them. The one you turn on last takes the fourth spot in the bottom bar; on a computer they are all in the left column.",
  "Spegnendo un modulo la voce sparisce dalla barra, ma quello che hai registrato resta dov'e: riaccendendolo lo ritrovi.": "Turning a module off removes it from the bar, but what you recorded stays where it is: turn it back on and you find it again.",
  "Persone, posti e idee salvate al volo.": "People, places and ideas saved on the fly.",
  "Consumi AI": "AI spend",
  "Quanto e costato questo mese": "What it has cost this month",
  "circa {v}": "about {v}",
  "non disponibile": "not available",
  "{mese}, dal giorno 1": "{mese}, since the 1st",
  "Sto leggendo i consumi...": "Reading your AI spend...",
  "Non sono riuscito a leggere i consumi": "I could not read your AI spend",
  "La richiesta non e andata a buon fine, quindi questa schermata non sa dirti niente: non vuol dire che non hai speso.": "The request did not go through, so this screen cannot tell you anything: it does not mean you have spent nothing.",
  "Questo mese l'AI non l'hai ancora usata": "You have not used AI yet this month",
  "Il conto riparte da zero il primo di ogni mese. Compare qualcosa appena racconti una giornata a voce o chiudi una giornata col riassunto.": "The count restarts from zero on the first of every month. Something shows up as soon as you tell a day out loud or close a day with its summary.",
  "Stima su {d} giornate, di cui {r} raccontate a voce.": "An estimate over {d} days, {r} of them told out loud.",
  "Stima su {d} giornate.": "An estimate over {d} days.",
  "Stima su una giornata, raccontata a voce.": "An estimate over one day, told out loud.",
  "Stima su una giornata.": "An estimate over one day.",
  "Stima su {r} registrazioni.": "An estimate over {r} recordings.",
  "Stima su una registrazione.": "An estimate over one recording.",
  "Stima sulle chiamate di questo mese.": "An estimate over this month's calls.",
  "Circa {c} centesimi a giornata.": "About {c} cents a day.",
  "Da cosa arriva": "Where it comes from",
  "Trascrizione della voce": "Voice transcription",
  "Recap del mese": "Monthly recap",
  "Titoli e sintesi delle giornate": "Day titles and summaries",
  "Persone, date e note di Memo": "People, dates and Memo notes",
  "1 registrazione": "1 recording",
  "{n} registrazioni": "{n} recordings",
  "1 registrazione . {m} minuti": "1 recording . {m} minutes",
  "{n} registrazioni . {m} minuti": "{n} recordings . {m} minutes",
  "{n} recap . il modello grande": "{n} recap . the large model",
  "1 giornata": "1 day",
  "{n} giornate": "{n} days",
  "1 chiamata in tutto": "1 call in total",
  "{n} chiamate in tutto": "{n} calls in total",
  "meno di {v}": "less than {v}",
  "E una stima, non la tua bolletta": "An estimate, not your bill",
  "I token sono quelli": "The tokens are the",
  "ufficiali": "official ones",
  "che OpenAI riporta a ogni risposta, quindi il conteggio e esatto. Il prezzo no: e un listino salvato ad agosto 2026 in": "OpenAI reports with every response, so the count is exact. The price is not: it is a price list saved in August 2026 in",
  ", e se OpenAI lo cambia questa cifra resta indietro finche non lo aggiorni. Il conto vero e sul tuo pannello OpenAI.": ", and if OpenAI changes it this figure stays behind until you update it. The real bill is on your OpenAI dashboard.",
  "Elimina l'account": "Delete account",
  "Cancella l'account e tutte le giornate dal cloud.": "Deletes your account and all your days from the cloud.",
  "Sicuro? Account e giornate spariscono anche dal cloud. Non si torna indietro.": "Sure? Account and days disappear from the cloud too. There is no way back.",
  "elimino...": "deleting...",
  "si, elimina": "yes, delete",
  "Accedi al tuo account": "Sign in to your account",
  "Il diario a voce e spento": "The spoken journal is off",
  "Trascrizione e rielaborazione girano su un server e costano a ogni minuto registrato.":
    "Transcription and processing run on a server and cost money for every minute recorded.",
  "Racconti e basta: parli, il testo si scrive":
    "You just talk: you speak, the text writes itself",
  "Scopri Premium": "See what Premium is",
  "disdici quando vuoi": "cancel whenever you want",
  "Foto profilo": "Profile photo",
  "Come ti vedi nel pallino in alto.": "How you look in the dot up top.",
  "Resta su questo account, non nel diario":
    "It stays on this account, not in your journal",
  "Scatta una foto": "Take a photo",
  "Scegli dalla libreria": "Choose from your library",
  "Togli la foto, torna all'iniziale": "Remove the photo, go back to the initial",
  "Sposta e ingrandisci": "Move and scale",
  "Ingrandisci": "Scale",
  "Usa questa foto": "Use this photo",
  "salvo...": "saving...",
  "Foto profilo aggiornata.": "Profile photo updated.",
  "Foto tolta. Resta la tua iniziale.": "Photo removed. Your initial stays.",
  "Non sono riuscito a leggere questa immagine.": "I could not read this image.",
  "Salvataggio non riuscito": "Could not save",
  "Il tuo nome": "Your name",
  "Cambia il tuo nome": "Change your name",
  "Come vuoi essere chiamato dentro l'app. L'email non cambia.":
    "What you want the app to call you. Your email does not change.",
  "Senza nome l'app ti chiama {n}, come la tua email.":
    "With no name the app calls you {n}, after your email.",
  "Adesso ti chiami {n}.": "You are now {n}.",
  "Nome tolto. Torna quello della tua email.":
    "Name removed. The one from your email is back.",
  "ospite": "guest",
  // L'interruttore Face ID (1 settembre 2026).
  "Face ID": "Face ID",
  "Il volto al posto del codice, quando apri l'app.":
    "Your face instead of the code, when you open the app.",
  "Face ID non attivato: la prova non e riuscita.":
    "Face ID not turned on: the check did not go through.",
  // --- Impostazioni > Cassaforte (R12) ---
  "Cassaforte": "Vault",
  "Cosa vede il server": "What the server sees",
  "Chiusa a chiave sul dispositivo: nessuno legge il tuo diario, noi compresi.": "Locked on your device: nobody reads your diary, us included.",
  "{n} giornate in chiaro": "{n} days in the clear",
  "{n} righe in chiaro": "{n} rows in the clear",
  "Per vedere il codice di recupero": "To see the recovery code",
  "{n} giornate sono ancora in chiaro sul server.": "{n} days are still in the clear on the server.",
  "{n} righe (memo, recap, domande) sono ancora in chiaro sul server.": "{n} rows (memos, recaps, questions) are still in the clear on the server.",
  "Sono state scritte prima della cassaforte. Chiuderle a chiave le rende illeggibili per chiunque non abbia la tua chiave, noi compresi. Ci vuole meno di un minuto e non tocca il testo.":
    "They were written before the vault. Locking them makes them unreadable to anyone without your key, us included. It takes less than a minute and does not touch the text.",
  "Chiudo a chiave... {fatte} di {totale}": "Locking... {fatte} of {totale}",
  "Chiudo a chiave...": "Locking...",
  "Chiudi a chiave le {n} giornate": "Lock the {n} days",
  "Chiudi a chiave tutto": "Lock everything",
  "Fatto: tutto quello che era in chiaro adesso e chiuso a chiave.": "Done: everything that was in the clear is now locked.",
  "Stato": "Status",
  "Tutto chiuso a chiave": "Everything locked",
  "{n} in chiaro": "{n} in the clear",
  "Giornate nella cassaforte": "Days in the vault",
  "La chiave su questo dispositivo": "The key on this device",
  "Nel portachiavi di iCloud": "In iCloud Keychain",
  "In questo browser": "In this browser",
  "Vedi il codice di recupero": "See the recovery code",
  "Di chi e ogni giornata, che giorno e, la versione, quando e stata scritta e quanto pesa.": "Whose each day is, which day it is, the version, when it was written and how much it weighs.",
  "Il testo, il titolo, la sintesi, le aree, i fatti, i memo e i recap: no.": "The text, the title, the summary, the areas, the facts, the memos and the recaps: no.",
  "Adesso: solo su questo dispositivo. Se lo perdi, o lo cambi senza un backup, le giornate non si recuperano.": "Right now: only on this device. If you lose it, or change it without a backup, the days cannot be recovered.",
  "Niente esce dal dispositivo, tranne il testo nel momento in cui l'AI ci lavora. Salva su file ogni tanto: la riga \"Esporta un backup\" e qui sopra.": "Nothing leaves the device, except the text at the moment the AI works on it. Save to a file now and then: the \"Export a backup\" row is just above.",
  "Anche sul server, chiuso a chiave": "On the server too, locked",
  "Metti una email. Le giornate salgono chiuse a chiave: nemmeno chi ha fatto l'app le legge. Le ritrovi se cambi telefono.": "Add an email. Your days go up locked: not even the people who made the app can read them. You get them back if you change phone.",
  "Il testo, quando l'AI ci lavora": "The text, when the AI works on it",
  "Racconto a voce, titolo, sintesi e aree passano da un server nel momento in cui li chiedi, con le giornate del regalo. Delle tue giornate sul server non resta niente.": "Voice, title, summary and areas go through a server at the moment you ask for them, with the gift days. Nothing of your days stays on the server.",
  "in pausa": "paused",
  "finito": "used up",
  "{n} giornate su {max}": "{n} days of {max}",
  "Un attimo: chiedo al server quante giornate restano.": "One moment: asking the server how many days are left.",
  "Il regalo e in pausa: per ora l'AI non lavora per chi non ha un abbonamento.": "The gift is paused: for now the AI does not work for anyone without a subscription.",
  "Le {max} giornate con l'AI in regalo sono finite.": "The {max} gift AI days are used up.",
  "{n} giornate su {max}, ancora con l'AI.": "{n} days of {max}, still with the AI.",
  "Come funziona": "How it works",
  "Le prime giornate le paga chi ha fatto questa app": "The first days are paid for by the people who made this app",
  "Racconto a voce, titolo, sintesi e aree. Una giornata conta una volta, anche se la riapri e la completi.": "Voice, title, summary and areas. A day counts once, even if you reopen and complete it.",
  "Quando finiscono, l'app continua": "When they run out, the app goes on",
  "Scrivi, salvi, rileggi. Manca solo la parte fatta dall'AI.": "You write, save, reread. Only the part done by the AI is missing.",
  "Il conto e legato a questo dispositivo, non all'app": "The count is tied to this device, not to the app",
  "Cancellare e reinstallare non lo azzera. Se metti una email, il conto ti segue e non ricomincia.": "Deleting and reinstalling does not reset it. If you add an email, the count follows you and does not start over.",
  "Il conto": "The count",
  "Usate": "Used",
  "Rimaste": "Left",
  "AI in regalo": "AI gift",
  "Poi": "Then",
  "AI senza limiti, backup ogni notte, i recap.": "Unlimited AI, nightly backup, recaps.",
  "Backup ogni notte": "Nightly backup",
  "Spento": "Off",
  "Metti una email: le giornate salgono chiuse a chiave e le ritrovi su iPad e sul computer. Premium ti segue.": "Add an email: your days go up locked and you find them on iPad and on the computer. Premium follows you.",
  "Email e codice, mai una password. Le giornate scritte qui salgono al primo accesso.": "Email and code, never a password. The days written here go up at first sign-in.",
};
