/**
 * Il catalogo inglese del modulo IMPOSTAZIONI (pannelli, tema, dati, consumi AI).
 *
 * Nato dallo spacchettamento di en.ts (passo C, ARCHITETTURA.md, 23
 * agosto 2026). Chiave = frase italiana esatta nel codice; le regole di
 * traduzione sono nel commento di en.ts. Una voce per riga, sempre
 * "chiave": "valore", — verify-i18n legge questo formato.
 */
export const IMPOSTAZIONI: Record<string, string> = {
  "Pacchetto": "Build",
  "aggiungi": "add",
  "togli": "remove",
  "Non hai mai fatto un backup": "You have never made a backup",
  "Non fai un backup da {n} giorni": "You have not made a backup in {n} days",
  "Le tue {n} giornate esistono solo su questo dispositivo. Se si rompe o lo formatti, non c'e nessuna copia da nessuna parte: non esiste un server dove cercarle. Esporta il file e mettilo dove tieni le cose che non vuoi perdere.": "Your {n} days exist only on this device. If it breaks or you wipe it, there is no copy anywhere: there is no server to look on. Export the file and put it where you keep the things you do not want to lose.",
  "Errore nella rimozione": "Removal error",
  "Tracker neutri, niente voti: rispondono a “oggi l'ho fatto?” e basta. Compaiono nella giornata come caselle da accendere.": "Neutral trackers, no grades: they answer “did I do it today?” and nothing else. They show up in your day as boxes to tick.",
  "Attivi . salvo...": "Active . saving...",
  "Attivi": "Active",
  "Nessun obiettivo": "No goals",
  "Aggiungine uno qui sotto: comparira subito nella giornata.": "Add one below: it will show up in your day right away.",
  "Aggiungi un obiettivo...": "Add a goal...",
  "Nuovo obiettivo": "New goal",
  "Il tema cambia solo come si vede l'app. Le tue giornate non le tocca nessuno.": "The theme only changes how the app looks. Nobody touches your days.",
  "la telefonata rimandata": "the phone call put off",
  "Trentadue minuti, e una frase alla fine.": "Thirty-two minutes, and one sentence at the end.",
  "attivo": "active",
  "Ogni tema esiste in chiaro e in scuro, e passa un controllo automatico sul contrasto: un tema che rende il testo illeggibile non diventa selezionabile.": "Every theme exists in light and dark, and passes an automatic contrast check: a theme that makes text unreadable never becomes selectable.",
  "Chiaro": "Light",
  "Scuro": "Dark",
  "Sistema": "System",
  "Ch": "Li",
  "Sc": "Da",
  "Sist": "Sys",
  "Nessuna riga del tuo diario e mai uscita da questo dispositivo.": "Not one line of your diary has ever left this device.",
  "Le tue giornate vivono sul tuo account e ti seguono su ogni dispositivo.": "Your days live on your account and follow you on every device.",
  "Dove stanno": "Where they are",
  "Non c'e un account, non c'e un server, non c'e niente da chiedere di cancellare. L'app non fa nemmeno una richiesta di rete.": "There is no account, no server, nothing to ask anyone to delete. The app does not even make one network request.",
  "Se il dispositivo si rompe": "If the device breaks",
  "Il diario e finito. Non esiste una copia da nessuna parte: l'unica rete di salvataggio e il backup che esporti tu.": "The diary is gone. There is no copy anywhere: the only safety net is the backup you export yourself.",
  "Cosa esce da qui": "What leaves this device",
  "Niente": "Nothing",
  "Voce, riassunti e recap sono spenti in questa modalita proprio perche girerebbero su un server.": "Voice, summaries and recaps are off in this mode precisely because they would run on a server.",
  "Sul tuo account, nel cloud": "On your account, in the cloud",
  "Ti seguono su ogni dispositivo dove fai l'accesso. Il backup qui sopra resta una copia in piu, tua.": "They follow you on every device you sign in on. The backup above stays an extra copy, yours.",
  "Quello che chiedi tu": "What you ask for",
  "Registrazione, riassunto e recap passano da un server per essere elaborati. Il resto no.": "Recording, summary and recaps go through a server to be processed. Nothing else does.",
  "Come il dispositivo": "Same as the device",
  "Ora sarebbe {lingua}.": "Right now that would be {lingua}.",
  "Cambia solo le parole dell'app. Quello che hai scritto tu resta come l'hai scritto.": "It only changes the app's words. What you wrote stays exactly as you wrote it.",
  "Lingua": "Language",
  "Torna a Impostazioni": "Back to Settings",
  "Backup esportato: {n} {giornate}. Mettilo dove tieni le cose che non vuoi perdere.": "Backup exported: {n} {giornate}. Put it where you keep the things you do not want to lose.",
  "Export non riuscito.": "Export failed.",
  "Import non riuscito.": "Import failed.",
  "Fatto. Questo dispositivo non contiene piu nessuna giornata.": "Done. This device no longer holds a single day.",
  "Cancellazione non riuscita.": "Deletion failed.",
  "Ospite": "Guest",
  "Questo dispositivo": "This device",
  "Come funziona e come si vede il tuo diario.": "How your diary works and how it looks.",
  "Apri Recap": "Open Recap",
  "Le tue giornate, raccontate.": "Your days, told.",
  "Mensili, semestrali, annuali. Una prosa narrativa che rilegge i tuoi mesi senza giudizio.": "Monthly, half-yearly, yearly. Narrative prose that reads your months back to you without judgement.",
  "Nessun recap generato ancora": "No recap generated yet",
  "Il diario": "The diary",
  "Le caselle che accendi ogni giorno.": "The boxes you tick every day.",
  "attivi": "active",
  "Lingua e aspetto": "Language and look",
  "Al primo avvio segue la lingua del dispositivo.": "On first launch it follows the device language.",
  "automatica": "automatic",
  "Tema": "Theme",
  "{n} temi inclusi, tutti in chiaro e in scuro.": "{n} themes included, all in light and dark.",
  "Chiaro o scuro": "Light or dark",
  "Vale per qualsiasi tema. Con Sistema segue il dispositivo.": "Applies to any theme. With System it follows the device.",
  "I tuoi dati": "Your data",
  "Esporta un backup": "Export a backup",
  "Un solo file con tutto: giornate, obiettivi, metriche, Ricorda.": "One file with everything: days, goals, metrics, Remember.",
  "esporto...": "exporting...",
  "Importa un backup": "Import a backup",
  "Aggiunge le giornate che mancano. Quelle che hai gia non le tocca.": "It adds the days you are missing. It never touches the ones you already have.",
  "importo...": "importing...",
  "Dove sono le mie giornate": "Where my days are",
  "Cosa esce da questo dispositivo, e cosa no.": "What leaves this device, and what does not.",
  "Account": "Account",
  "Dove": "Where",
  "Email": "Email",
  "Ospite (cloud)": "Guest (cloud)",
  "Piano": "Plan",
  "Gratis": "Free",
  "Versione": "Version",
  "Esci dall'account": "Log out",
  "esco...": "logging out...",
  "Esco...": "Logging out...",
  "Zona pericolosa": "Danger zone",
  "Cancella tutte le giornate": "Delete all days",
  "Sicuro? Le elimina da questo dispositivo. Non si torna indietro.": "Sure? This deletes them from this device. There is no way back.",
  "Da questo dispositivo. Non si torna indietro.": "From this device. There is no way back.",
  "cancello...": "deleting...",
  "si, cancella": "yes, delete",
  "Passa a Premium": "Go Premium",
  "Dimensione del testo": "Text size",
  "Ingrandisce tutta l'app, non solo le scritte.": "Makes the whole app bigger, not just the words.",
  "Ingrandisce tutta l'app: scritte, tasti e spazi insieme. Cosi niente si accavalla.": "Makes the whole app bigger: words, buttons and spacing together. That way nothing overlaps.",
  "Anteprima": "Preview",
  "Torna alla misura normale": "Back to the normal size",
  "Quota inclusa nell'abbonamento": "Quota included in your subscription",
  "{n} token usati questo mese. La quota si azzera il primo del mese.": "{n} tokens used this month. The quota resets on the first of the month.",
  "Moduli": "Modules",
  "Sezioni in piu: palestra, cibo, sonno.": "Extra sections: gym, food, sleep.",
  "nessuno": "none",
  "Presto": "Coming soon",
  "presto": "soon",
  "Sezioni in piu, accese solo se le vuoi. Quella che accendi per ultima prende il quarto posto nella barra in basso; sul computer ci sono tutte nella colonna di sinistra.": "Extra sections, on only if you want them. The one you turn on last takes the fourth spot in the bottom bar; on a computer they are all in the left column.",
  "Spegnendo un modulo la voce sparisce dalla barra, ma quello che hai registrato resta dov'e: riaccendendolo lo ritrovi.": "Turning a module off removes it from the bar, but what you recorded stays where it is: turn it back on and you find it again.",
  "Persone, posti e idee salvate al volo.": "People, places and ideas saved on the fly.",
  "Consumi AI": "AI spend",
  "Quanto e costato questo mese": "What it has cost this month",
  "circa {v}": "about {v}",
  "non disponibile": "not available",
  "{mese}, dal giorno 1": "{mese}, since the 1st",
  "Sto leggendo i consumi...": "Reading your AI spend...",
  "Non sono riuscito a leggere i consumi": "I could not read your AI spend",
  "La richiesta non e andata a buon fine, quindi questa schermata non sa dirti niente: non vuol dire che non hai speso.": "The request did not go through, so this screen cannot tell you anything: it does not mean you have spent nothing.",
  "Questo mese l'AI non l'hai ancora usata": "You have not used AI yet this month",
  "Il conto riparte da zero il primo di ogni mese. Compare qualcosa appena racconti una giornata a voce o chiudi una giornata col riassunto.": "The count restarts from zero on the first of every month. Something shows up as soon as you tell a day out loud or close a day with its summary.",
  "Stima su {d} giornate, di cui {r} raccontate a voce.": "An estimate over {d} days, {r} of them told out loud.",
  "Stima su {d} giornate.": "An estimate over {d} days.",
  "Stima su una giornata, raccontata a voce.": "An estimate over one day, told out loud.",
  "Stima su una giornata.": "An estimate over one day.",
  "Stima su {r} registrazioni.": "An estimate over {r} recordings.",
  "Stima su una registrazione.": "An estimate over one recording.",
  "Stima sulle chiamate di questo mese.": "An estimate over this month's calls.",
  "Circa {c} centesimi a giornata.": "About {c} cents a day.",
  "Da cosa arriva": "Where it comes from",
  "Trascrizione della voce": "Voice transcription",
  "Recap del mese": "Monthly recap",
  "Titoli e sintesi delle giornate": "Day titles and summaries",
  "Persone, date e note di Ricorda": "People, dates and Remember notes",
  "1 registrazione": "1 recording",
  "{n} registrazioni": "{n} recordings",
  "1 registrazione . {m} minuti": "1 recording . {m} minutes",
  "{n} registrazioni . {m} minuti": "{n} recordings . {m} minutes",
  "{n} recap . il modello grande": "{n} recap . the large model",
  "1 giornata": "1 day",
  "{n} giornate": "{n} days",
  "1 chiamata in tutto": "1 call in total",
  "{n} chiamate in tutto": "{n} calls in total",
  "meno di {v}": "less than {v}",
  "E una stima, non la tua bolletta": "An estimate, not your bill",
  "I token sono quelli": "The tokens are the",
  "ufficiali": "official ones",
  "che OpenAI riporta a ogni risposta, quindi il conteggio e esatto. Il prezzo no: e un listino salvato ad agosto 2026 in": "OpenAI reports with every response, so the count is exact. The price is not: it is a price list saved in August 2026 in",
  ", e se OpenAI lo cambia questa cifra resta indietro finche non lo aggiorni. Il conto vero e sul tuo pannello OpenAI.": ", and if OpenAI changes it this figure stays behind until you update it. The real bill is on your OpenAI dashboard.",
  "Elimina l'account": "Delete account",
  "Cancella l'account e tutte le giornate dal cloud.": "Deletes your account and all your days from the cloud.",
  "Sicuro? Account e giornate spariscono anche dal cloud. Non si torna indietro.": "Sure? Account and days disappear from the cloud too. There is no way back.",
  "elimino...": "deleting...",
  "si, elimina": "yes, delete",
  "Accedi al tuo account": "Sign in to your account",
  "Il diario a voce e spento": "The spoken journal is off",
  "Trascrizione e rielaborazione girano su un server e costano a ogni minuto registrato.":
    "Transcription and processing run on a server and cost money for every minute recorded.",
  "Racconti e basta: parli, il testo si scrive":
    "You just talk: you speak, the text writes itself",
  "Scopri Premium": "See what Premium is",
  "disdici quando vuoi": "cancel whenever you want",
};
