/**
 * Le traduzioni del modulo ADMIN (unite dal runtime i18n via
 * src/lib/i18n/en.ts). Il pannello lo vede una persona sola, ma le regole
 * sono le stesse dell'app: testo a schermo sempre via t().
 */
export const ADMIN: Record<string, string> = {
  "Admin": "Admin",
  "Aree": "Areas",
  "Obiettivi di default": "Default goals",
  "Messaggio di benvenuto": "Welcome message",
  "Modelli AI": "AI models",
  "Piani e limiti": "Plans and limits",
  "l'unico che entra qui": "the only one who gets in here",
  "Le caselle in cui l'AI divide una giornata. L'ordine e quello in cui si leggono nella schermata del giorno.": "The boxes the AI splits a day into. The order is the one they are read in on the day screen.",
  "Aggiungi area": "Add area",
  "Salva le modifiche": "Save changes",
  "Salvataggio...": "Saving...",
  "Salvato. La prossima giornata raccontata usa gia queste aree.": "Saved. The next day you tell already uses these areas.",
  "A un'area manca il nome (italiano o inglese): completala o toglila.": "An area is missing its name (Italian or English): complete it or remove it.",
  "Il salvataggio non e riuscito. Riprova.": "Saving did not work. Try again.",
  "Nome": "Name",
  "Inglese": "English",
  "Cosa ci va (lo legge l'AI)": "What goes in it (the AI reads this)",
  "Attiva": "Active",
  "Sposta su": "Move up",
  "Sposta giu": "Move down",
  "(senza nome)": "(unnamed)",
  "nuova": "new",
  "Area nuova": "New area",
  "Nome (italiano)": "Name (Italian)",
  "Nome (inglese)": "Name (English)",
  "Chiave": "Key",
  "Si sceglie una volta e non si cambia piu: e cio che viene scritto dentro ogni giornata. Per un'area nuova e il nome con cui nasce.": "Chosen once and never changed: it is what gets written inside every day. For a new area it is the name it is born with.",
  "Cosa ci va": "What goes in it",
  "Finisce nelle istruzioni dell'AI, parola per parola. Le frasi che dicono cosa NON ci va sono quelle che funzionano meglio.": "Goes into the AI instructions, word for word. The sentences that say what does NOT belong are the ones that work best.",
  "Icona": "Icon",
  "Facoltativa. I disegni esistenti: lavoro, relazioni, cibo, movimento, emozioni. Vuota = nessun disegno (Corpo non ne ha mai avuto uno).": "Optional. Existing drawings: lavoro, relazioni, cibo, movimento, emozioni. Empty = no drawing (Corpo never had one).",
  "Chiudi": "Close",
  "Prima di salvare, tre cose che succedono davvero": "Before saving, three things that really happen",
  "Le giornate gia salvate non si riclassificano: cio che e stato assegnato resta dov'e.": "Days already saved are not reclassified: what was assigned stays where it is.",
  "Ogni casella in piu e una scelta in piu per l'AI: con troppe caselle, qualcuna restera vuota quasi sempre.": "Every extra box is an extra choice for the AI: with too many boxes, some will stay empty almost always.",
  "Un'area spenta non cancella nulla: smette di essere assegnata da oggi, e le giornate vecchie continuano a mostrarla.": "A switched-off area deletes nothing: it stops being assigned from today, and old days keep showing it.",
  "Chi tiene il diario sul telefono in modalita locale vede le aree cotte dentro il pacchetto: le aree nuove arrivano li solo con una build nuova dell'app.": "Whoever keeps the diary on the phone in local mode sees the areas baked into the bundle: new areas get there only with a new build of the app.",
};
