/**
 * Le traduzioni del modulo ADMIN (unite dal runtime i18n via
 * src/lib/i18n/en.ts). Il pannello lo vede una persona sola, ma le regole
 * sono le stesse dell'app: testo a schermo sempre via t().
 */
export const ADMIN: Record<string, string> = {
  "Admin": "Admin",
  "Aree": "Areas",
  "Obiettivi di default": "Default goals",
  "Messaggio di benvenuto": "Welcome message",
  "Modelli AI": "AI models",
  "Piani e limiti": "Plans and limits",
  "l'unico che entra qui": "the only one who gets in here",
  "Le caselle in cui l'AI divide una giornata. L'ordine e quello in cui si leggono nella schermata del giorno.": "The boxes the AI splits a day into. The order is the one they are read in on the day screen.",
  "Aggiungi area": "Add area",
  "Salva le modifiche": "Save changes",
  "Salvataggio...": "Saving...",
  "Salvato. La prossima giornata raccontata usa gia queste aree.": "Saved. The next day you tell already uses these areas.",
  "A un'area manca il nome (italiano o inglese): completala o toglila.": "An area is missing its name (Italian or English): complete it or remove it.",
  "Il salvataggio non e riuscito. Riprova.": "Saving did not work. Try again.",
  "Nome": "Name",
  "Inglese": "English",
  "Cosa ci va (lo legge l'AI)": "What goes in it (the AI reads this)",
  "Attiva": "Active",
  "Sposta su": "Move up",
  "Sposta giu": "Move down",
  "(senza nome)": "(unnamed)",
  "nuova": "new",
  "Area nuova": "New area",
  "Nome (italiano)": "Name (Italian)",
  "Nome (inglese)": "Name (English)",
  "Chiave": "Key",
  "Si sceglie una volta e non si cambia piu: e cio che viene scritto dentro ogni giornata. Per un'area nuova e il nome con cui nasce.": "Chosen once and never changed: it is what gets written inside every day. For a new area it is the name it is born with.",
  "Cosa ci va": "What goes in it",
  "Finisce nelle istruzioni dell'AI, parola per parola. Le frasi che dicono cosa NON ci va sono quelle che funzionano meglio.": "Goes into the AI instructions, word for word. The sentences that say what does NOT belong are the ones that work best.",
  "Icona": "Icon",
  "Facoltativa. I disegni esistenti: lavoro, relazioni, cibo, movimento, emozioni. Vuota = nessun disegno (Corpo non ne ha mai avuto uno).": "Optional. Existing drawings: lavoro, relazioni, cibo, movimento, emozioni. Empty = no drawing (Corpo never had one).",
  "Chiudi": "Close",
  "Prima di salvare, tre cose che succedono davvero": "Before saving, three things that really happen",
  "Le giornate gia salvate non si riclassificano: cio che e stato assegnato resta dov'e.": "Days already saved are not reclassified: what was assigned stays where it is.",
  "Ogni casella in piu e una scelta in piu per l'AI: con troppe caselle, qualcuna restera vuota quasi sempre.": "Every extra box is an extra choice for the AI: with too many boxes, some will stay empty almost always.",
  "Un'area spenta non cancella nulla: smette di essere assegnata da oggi, e le giornate vecchie continuano a mostrarla.": "A switched-off area deletes nothing: it stops being assigned from today, and old days keep showing it.",
  "Chi tiene il diario sul telefono in modalita locale vede le aree cotte dentro il pacchetto: le aree nuove arrivano li solo con una build nuova dell'app.": "Whoever keeps the diary on the phone in local mode sees the areas baked into the bundle: new areas get there only with a new build of the app.",

  /* La schermata Messaggio di benvenuto. */
  "Il riquadro che si apre una volta per ogni apertura dell'app. Si cambia da qui, senza rifare l'app: al prossimo avvio i telefoni collegati leggono il testo nuovo.": "The box that opens once every time the app is opened. You change it from here, without rebuilding the app: at the next start, connected phones read the new text.",
  "Salvato. Chi apre l'app da adesso legge il testo nuovo.": "Saved. Whoever opens the app from now on reads the new text.",
  "Non sono riuscito a leggere il messaggio.": "I could not read the message.",
  "Fatto: al prossimo avvio il messaggio torna per tutti, una volta.": "Done: at the next start the message comes back for everyone, once.",
  "Mostra il messaggio": "Show the message",
  "Spento, non lo vede piu nessuno.": "Switched off, nobody sees it any more.",
  "Mostralo di nuovo a tutti": "Show it again to everyone",
  "Chi ha spuntato \"non mostrare piu\" non vedrebbe il testo nuovo. Questo tasto azzera tutte le spunte: al prossimo avvio il messaggio torna per tutti, una volta.": "Whoever ticked \"do not show again\" would not see the new text. This button clears every tick: at the next start the message comes back for everyone, once.",
  "Mostralo di nuovo": "Show it again",
  "Salva prima le modifiche.": "Save your changes first.",
  "Il testo": "The text",
  "Se l'inglese resta vuoto, chi ha il telefono in inglese vede l'italiano: meglio una frase nella lingua sbagliata che un riquadro vuoto.": "If the English is left empty, whoever has their phone in English sees the Italian: better a sentence in the wrong language than an empty box.",
  "Italiano": "Italian",
  "Occhiello": "Kicker",
  "Promessa": "Promise",
  "Riga in evidenza": "Highlighted line",
  "Riga vuota = paragrafo nuovo. *fra asterischi* = grassetto.": "Empty line = new paragraph. *between asterisks* = bold.",
  "Firma": "Signature",
  "Testo del bottone": "Button text",
  "Riga in fondo (facoltativa)": "Bottom line (optional)",
  "Indirizzo della riga in fondo": "Address for the bottom line",
  "Vuoto, la riga in fondo non compare e la linguetta Feedback resta muta: un invito che non porta da nessuna parte e una promessa rotta al primo tocco. Appena c'e un indirizzo, si accendono tutte e due.": "Empty, the bottom line does not appear and the Feedback tab stays mute: an invitation that leads nowhere is a promise broken at the first tap. As soon as there is an address, both light up.",
  "La foto": "The photo",
  "Quella tonda sopra il bordo. Si ritaglia al centro in quadrato e si riduce a 320px.": "The round one above the edge. It is cropped square from the centre and reduced to 320px.",
  "PNG o JPEG. Viene ritagliata al centro: se conta l'inquadratura, ritagliala prima tu.": "PNG or JPEG. It is cropped from the centre: if the framing matters, crop it yourself first.",
  "Il logo": "The logo",
  "Di fabbrica sono i due loghi dell'app, scelti da soli in base al tema. Qui si mette un logo diverso solo per il benvenuto, senza toccare splash, login e rail.": "Out of the box these are the app's two logos, picked on their own from the theme. Here you set a logo used only for the welcome, without touching splash, login and rail.",
  "Sui temi chiari": "On light themes",
  "Sui temi scuri": "On dark themes",
  "PNG con fondo trasparente. Sta sopra un fondo chiaro, quindi serve un segno scuro.": "PNG with a transparent background. It sits on a light background, so it needs a dark mark.",
  "PNG con fondo trasparente. Sta sopra un fondo scuro, quindi serve un segno chiaro.": "PNG with a transparent background. It sits on a dark background, so it needs a light mark.",
  "Scegli un file": "Choose a file",
  "Rimetti quella di fabbrica": "Put the original back",
  "Sostituita da te": "Replaced by you",
  "Quella di fabbrica": "The original one",
  "L'immagine resta troppo grande anche dopo la riduzione: provane un'altra.": "The image is still too large even after being reduced: try another one.",
  "Questa immagine non si riesce ad aprire.": "This image cannot be opened.",
  "Tre cose che succedono davvero": "Three things that really happen",
  "Il testo nuovo si vede al prossimo avvio dell'app, non subito su chi la sta gia usando.": "The new text shows at the next start of the app, not straight away for whoever is already using it.",
  "Chi tiene il diario sul telefono in modalita locale non chiede niente alla rete: vede il testo cotto dentro il pacchetto, e quello nuovo arriva li solo con una build nuova dell'app.": "Whoever keeps the diary on their phone in local mode asks the network for nothing: they see the text baked into the bundle, and the new one gets there only with a new build of the app.",
  "Foto e loghi viaggiano dentro la riga, non in un deposito file: il tetto e 48 KB per immagine, come per la foto profilo.": "Photo and logos travel inside the row, not in a file store: the cap is 48 KB per image, as for the profile photo.",
};
