/**
 * Il catalogo inglese del modulo OGGI: editor, registrazione, giornata raccontata,
 * metriche, obiettivi, /giorno.
 *
 * Nato dallo spacchettamento di en.ts (passo C, ARCHITETTURA.md, 23
 * agosto 2026). Chiave = frase italiana esatta nel codice; le regole di
 * traduzione sono nel commento di en.ts. Una voce per riga, sempre
 * "chiave": "valore", — verify-i18n legge questo formato.
 */
export const OGGI: Record<string, string> = {
  "Errore": "Error",
  "Conferma": "Confirm",
  "Continua": "Continue",
  "Esci": "Exit",
  "Salta": "Skip",
  "vedi": "see",
  "ok": "ok",
  "annulla": "cancel",
  "Eliminare questa giornata? Non puoi annullare.": "Delete this day? You cannot undo this.",
  "modifica": "edit",
  "Elimina giornata": "Delete day",
  "Bozza salvata in automatico": "Draft saved automatically",
  "comandi": "commands",
  "salva e basta": "just save",
  "chiudi la giornata": "close the day",
  "salva la giornata": "save the day",
  "Scrivi due righe.\nSenza pensarci troppo.": "Write a couple of lines.\nWithout overthinking it.",
  "Apri il microfono e racconta.\nSenza pensarci troppo.": "Open the mic and talk.\nWithout overthinking it.",
  "giornata raccontata, l'AI non ha ancora generato un titolo": "day told, the AI has not generated a title yet",
  "Con premium questa giornata avrebbe un titolo, una sintesi e le macro-aree. E la puoi raccontare a voce, invece di scriverla.": "With premium this day would have a title, a summary and its areas. And you could talk it out loud instead of typing it.",
  "aree macro non ancora estratte": "areas not extracted yet",
  "Scrivi la tua giornata": "Write your day",
  "senza parlare a voce alta": "without saying it out loud",
  "Racconta la tua giornata: come hai dormito e di che umore ti senti, cosa hai mangiato e fatto, chi hai visto e cosa hai provato. Aggiungi se vuoi peso, esercizio, crescita, corsi, cio che vuoi ricordare e quello che hai capito di te.\n\nEsempio: \u201cOggi ho dormito 7 ore ed ero serena. Ho lavorato, visto Giulia, fatto una passeggiata e capito che uscire mi fa stare meglio. Poi ho fatto colazione con fiocchi d'avena e yogurt. In ufficio ho incontrato...\u201d": "Tell your day: how you slept and how you feel, what you ate and did, who you saw and what you felt. If you like, add weight, exercise, growth, courses, what you want to remember and what you understood about yourself.\n\nExample: \u201cToday I slept 7 hours and felt calm. I worked, saw Giulia, went for a walk and realised that going out makes me feel better. Then I had oats and yogurt for breakfast. At the office I met...\u201d",
  "continua . poi rileggi e l'ai elabora la giornata": "continue . then read it back and the ai processes the day",
  "peso": "weight",
  "Peso in kg": "Weight in kg",
  "Meno": "Minus",
  "Piu": "Plus",
  "peso kg": "weight kg",
  "sonno": "sleep",
  "Ore di sonno": "Hours of sleep",
  "Minuti di sonno": "Minutes of sleep",
  "mood": "mood",
  "Peso": "Weight",
  "Mood": "Mood",
  "non segnato": "not set",
  "molto bene": "very good",
  "bene": "good",
  "cosi cosi": "so-so",
  "giu": "down",
  "male": "bad",
  "La giornata": "The day",
  "{fatti} su {totali}": "{fatti} of {totali}",
  // Non e l'area macro (quella ha nome e traduzione nella tabella `aree`):
  // e il TIPO di una cosa nei chiarimenti ("una persona", "un posto",
  // "lavoro"), vedi chiarimenti-screen.tsx.
  "Lavoro": "Work",
  "persone di oggi": "people from today",
  "Ho riconosciuto chi hai nominato. Controlla i nomi (potrei aver sbagliato lo spelling), poi salvali in Memo.": "I picked up who you mentioned. Check the names (I may have got the spelling wrong), then save them to Memo.",
  "gia in ricorda": "already in remember",
  "nuove . tocca per correggere": "new . tap to fix",
  "nuove persone": "new people",
  "Nome persona": "Person name",
  "persona": "person",
  "+ aggiungi persona": "+ add person",
  "Salvo...": "Saving...",
  "Salva e continua": "Save and continue",
  "Il microfono non si e avviato. Chiudi e riapri, oppure riavvia l'app.": "The microphone did not start. Close and reopen, or restart the app.",
  "Questo browser non sa registrare l'audio. Prova a scrivere a mano.": "This browser cannot record audio. Try typing instead.",
  "Permesso microfono negato. Vai nelle impostazioni del browser e abilitalo.": "Microphone permission denied. Go to your browser settings and allow it.",
  "Preparo il microfono.": "Getting the mic ready.",
  "Lascia per fermare.": "Let go to stop.",
  "Riprendi quando vuoi.": "Pick it up again whenever you want.",
  "Tieni premuto e racconta.": "Press and hold, then talk.",
  "pronto": "ready",
  "connetto": "connecting",
  "errore": "error",
  "in ascolto": "listening",
  "Trascrivo quello che hai detto...": "Transcribing what you said...",
  "Sto mandando la registrazione intera: cosi i nomi propri vengono scritti giusti.": "I am sending the whole recording: that way proper names come out right.",
  "Errore sconosciuto.": "Unknown error.",
  "Tieni premuto per parlare": "Press and hold to talk",
  "Le parole arrivano quando premi Fine.": "The words arrive when you press Done.",
  "Fine e salva": "Done and save",
  "Scrivi a mano": "Type it",
  "Rileggi prima di processare": "Read it back before processing",
  "correggi nomi e parole": "fix names and words",
  "Trascrizione vuota.": "Empty transcript.",
  "conferma . l'ai genera headline e aree macro sul testo corretto": "confirm . the ai generates the headline and areas from the corrected text",
  "bozza non salvata, recuperata": "unsaved draft, recovered",
  "Errore salvataggio persone": "Error saving people",
  "Errore eliminazione": "Deletion error",
  "Salvato su {n} giorni": "Saved across {n} days",
  "Registra di nuovo": "Record again",
  "niente catturato": "nothing captured",
  "Non ho sentito nulla.": "I did not hear anything.",
  "Forse il microfono era spento o c'era troppo rumore. Riprova da un posto tranquillo.": "Maybe the mic was off or it was too noisy. Try again somewhere quiet.",
  "elaborazione": "processing",
  "Leggo il racconto": "Reading your day",
  "Salvo la giornata": "Saving the day",
  "Controllo cosa non e chiaro": "Checking what is unclear",
  "Di solito ci vuole meno di un minuto.": "It usually takes less than a minute.",
  "Ci vuole un po' piu del solito. Ancora un momento.": "Taking a bit longer than usual. One more moment.",
  "Eliminare definitivamente questa giornata?": "Permanently delete this day?",
  "Modifica transcript": "Edit transcript",
  "al salvataggio . headline e aree vengono rigenerate": "on save . headline and areas are regenerated",
  "Aggiungi a questa giornata": "Add to this day",
  "Scrivi altro": "Write more",
  "Si aggiunge in fondo a quello che c'e gia": "It gets added below what is already there",
  "Con la data del {giorno} gia impostata": "With {giorno} already set as the date",
  "Salva in Memo": "Save to Memo",
  "Una persona, un posto, un'idea di quel giorno": "A person, a place, an idea from that day",
  "Com'e andato {giorno}?": "How was {giorno}?",
  "Raccontalo adesso: resta quel giorno,\nnon diventa oggi.": "Tell it now: it stays on that day,\nit does not become today.",
  "Racconta il {giorno}": "Tell {giorno}",
  "Salvo nella giornata...": "Saving to the day...",
  "Aggiunto alla giornata": "Added to the day",
  "Salvato sul {giorno}": "Saved on {giorno}",
  "Non sono riuscito a salvare. Riprova.": "I could not save it. Try again.",
  "Salvo in Memo...": "Saving to Memo...",
  "Salvato in Memo": "Saved to Memo",
  "Salvo le modifiche...": "Saving your changes...",
  "Salvato": "Saved",
  "Elimino la giornata...": "Deleting the day...",
  "Giornata eliminata": "Day deleted",
  "tuo": "yours",
  "tocca fuori per salvare": "tap outside to save",
  "titolo della giornata": "day title",
  "modifica il titolo della giornata": "edit the day title",
  "non sono riuscito a salvare il titolo": "could not save the title",
  "Da chiarire": "To clear up",
  "{n} di {tot}": "{n} of {tot}",
  "Da adesso lo riconosco con questo nome in tutto il diario.": "From now on I will recognise them by this name across the whole journal.",
  "Un altro nome": "Another name",
  "lo scrivo io": "I will type it",
  "Fine": "Done",
  "Avanti": "Next",
  "Persone incontrate": "People you saw",
  "Luoghi visitati": "Places you went",
  "togli {nome} da questa giornata": "remove {nome} from this day",
  "tolti da questa giornata:": "removed from this day:",
  "rimetti {nome}": "put {nome} back",
  "Non adesso": "Not now",
  "basta per adesso": "enough for now",
  "Non e una persona": "Not a person",
  "non chiedermelo piu": "stop asking me this",
  "Puoi sceglierne piu di una.": "You can pick more than one.",
  "Non c'entra con nessuna sfera": "It does not belong to any area",
  "era solo una cosa da fare": "it was just something I did",
  "indietro": "back",
  "Una persona": "A person",
  "Un posto": "A place",
  "Qualcosa da mangiare": "Something to eat",
  "Un'attivita": "An activity",
  "Ho tenuto aperto il microfono ma non e arrivato audio. Riprova, e se succede ancora mandami questa riga.":
    "The microphone was open but no audio came through. Try again, and if it keeps happening send me this line.",
  "La registrazione c'e, ma non sono riuscito a trascriverla.":
    "The recording is there, but I could not turn it into words.",
  "Sembra che non ci sia connessione.": "It looks like there is no connection.",
  "La rete non ha risposto in tempo.": "The network did not answer in time.",
  "Il racconto e ancora qui: controlla la connessione e premi di nuovo Fine.":
    "Your story is still here: check the connection and tap Done and save again.",
  "Giorno prima": "Previous day",
  "Giorno dopo": "Next day",
  "Scegli il giorno": "Choose the day",
  "Domani non e ancora successo": "Tomorrow has not happened yet",
  "Aggiungi dal rullino": "Add from camera roll",
  "Foto di quel giorno, dal telefono": "Photos of that day, from your phone",
  "Foto del giorno": "Photos of the day",
  "foto {indice} di {totale}": "photo {indice} of {totale}",
  "{indice} di {totale}": "{indice} of {totale}",
  "Mostra tutte le {n} foto": "Show all {n} photos",
  "Togliere questa foto dalla giornata? Il rullino resta com'e.":
    "Remove this photo from this day? Your camera roll stays untouched.",
  "Foto eliminata": "Photo removed",
  "Elimina dalla giornata": "Remove from this day",
  "Aggiungo le foto...": "Adding the photos...",
  "Foto aggiunta": "Photo added",
  "{n} foto aggiunte": "{n} photos added",
  "Non sono riuscito ad aggiungere le foto. Riprova.":
    "I could not add the photos. Try again.",
};
