/**
 * Il catalogo inglese del modulo ABBONAMENTO (muro premium, checkout finto).
 *
 * Nato dallo spacchettamento di en.ts (passo C, ARCHITETTURA.md, 23
 * agosto 2026). Chiave = frase italiana esatta nel codice; le regole di
 * traduzione sono nel commento di en.ts. Una voce per riga, sempre
 * "chiave": "valore", — verify-i18n legge questo formato.
 */
export const ABBONAMENTO: Record<string, string> = {
  "non ora": "not now",
  "Le giornate con l'AI\nin regalo sono finite": "The days with AI\nyou got as a gift are over",
  "Le {n} giornate con l'AI\nin regalo sono finite": "The {n} days with AI\nyou got as a gift are over",
  "Continua a scrivere. Manca solo l'AI.": "Keep writing. Only the AI is missing.",
  "Prova tutto, gratis. Poi decidi.": "Try everything, free. Then decide.",
  "Si attiva dall'app per iPhone. {n} giorni gratis, poi {prezzo}.": "Activated from the iPhone app. {n} days free, then {prezzo}.",
  "Annuale": "Yearly",
  "Mensile": "Monthly",
  "{n} giorni gratis, poi {prezzo} {periodo}. Disdici quando vuoi.": "{n} days free, then {prezzo} {periodo}. Cancel anytime.",
  "Disdici quando vuoi.": "Cancel anytime.",
  "Il negozio non risponde: riprova fra poco.": "The store is not responding: try again in a moment.",
  "L'app per iPhone sta arrivando sull'App Store: premium si attiva da li.": "The iPhone app is coming to the App Store: premium is activated from there.",
  "L'acquisto aspetta un'approvazione (In famiglia): premium si accende da solo appena arriva.": "The purchase is waiting for approval (Family Sharing): premium turns on by itself as soon as it arrives.",
  "Prova gratis {n} giorni": "Try {n} days free",
  "Abbonati": "Subscribe",
  "Passa a premium": "Go premium",
  "Scarica dayalogue per iPhone": "Get dayalogue for iPhone",
  "Continua senza AI": "Continue without AI",
  "Ripristina acquisti": "Restore purchases",
  "Termini": "Terms",
  "Privacy": "Privacy policy",
  "Poi si rinnova da solo a {prezzo} {periodo}. Disdici quando vuoi.": "Then it renews automatically at {prezzo} {periodo}. Cancel anytime.",
  "Si rinnova da solo a {prezzo} {periodo}. Disdici quando vuoi.": "Renews automatically at {prezzo} {periodo}. Cancel anytime.",
  "Voce, titolo, sintesi, aree, persone, recap.": "Voice, title, summary, areas, people, recaps.",
  "Chiuso a chiave, con backup ogni notte.": "Locked with your key, backed up every night.",
  "all'anno": "per year",
  "alla settimana": "per week",
  "al giorno": "per day",
  "un attimo...": "one moment...",
  "Per raccontare a voce\nserve premium": "Telling your day out loud\nneeds premium",
  "Per il titolo e la sintesi\nserve premium": "The title and the summary\nneed premium",
  "Per i recap del mese\nserve premium": "Monthly recaps\nneed premium",
  "Per le letture sui pattern\nserve premium": "Pattern readings\nneed premium",
  "Racconti e basta": "You just talk",
  "Su tutti i dispositivi": "On every device",
  "pagamento simulato . nessun addebito": "simulated payment . no charge",
  "ambiente di prova": "test environment",
  "dayalogue\nPremium": "dayalogue\nPremium",
  "Questa pagina non e collegata a nessun sistema di pagamento. Serve a provare l'app come la vede chi ha pagato.": "This page is not connected to any payment system. It is here so you can try the app the way a paying user sees it.",
  "al mese": "per month",
  "Non verra addebitato nulla.": "Nothing will be charged.",
  "Simula pagamento riuscito": "Simulate a successful payment",
  "Simula pagamento fallito": "Simulate a failed payment",
  "Annulla e torna al diario": "Cancel and go back to the journal",
  "Riporta questo account al piano gratis": "Put this account back on the free plan",
  "Pagina visibile solo in ambiente di prova e solo agli account autorizzati. Il piano viene scritto dal server, mai dal browser.": "This page is visible only in the test environment and only to allowed accounts. The plan is written by the server, never by the browser.",
  "Il pagamento non e andato a buon fine. Non e stato addebitato nulla e il tuo piano non e cambiato.": "The payment did not go through. Nothing was charged and your plan has not changed.",
  "Pagamento non riuscito. Sei ancora al piano gratis.": "Payment failed. You are still on the free plan.",
  "Attivo il premium...": "Turning on premium...",
  "Torno al piano gratis...": "Going back to the free plan...",
  "Sei tornato al piano gratis": "You are back on the free plan",
  "Non sono riuscito a cambiare il piano.": "I could not change the plan.",
  "Sei premium": "You are premium",
  "Da adesso l'app lavora insieme a te. Ecco cosa e cambiato.": "From now on the app works alongside you. Here is what changed.",
  "Racconti a voce, il testo si scrive da solo": "Speak, and the text writes itself",
  "Titolo, sintesi e macro-aree di ogni giornata": "A title, a summary and the macro-areas of every day",
  "Recap del mese e letture sui pattern": "Monthly recaps and readings on your patterns",
  "Provalo adesso": "Try it now",
  "Ho gia un account": "I already have an account",
  "L'AI ha chiuso\nquesta giornata per te": "The AI closed\nthis day for you",
  "Titolo, sintesi, aree: li ha scritti lei. Ne hai altre {n} in regalo.": "Title, summary, areas: it wrote them. You have {n} more as a gift.",
  "Titolo, sintesi, aree: li ha scritti lei. Le prime giornate sono in regalo.": "Title, summary, areas: it wrote them. The first days are a gift.",
};
